### ISSUE TITLE
analyze the library or single program without main function

### ISSUE THREAD

**Issue by flyfish101** [GaloisInc/MATE#61]
How to analyze the library or single program without main function?  "mate-cli oneshot"  command doesn't  work on library.

**Comment by thinkmoore** [comment]
Hi @flyfish101!

To analyze a library or program without a main function, you'll need to write a "harness" that contains a main function and exercises the functionality of the library you are interested in exploring, much like a test or fuzzing harness. (The analysis is "top-down", so only code reachable from the entry point will be considered.) To ensure that the code is properly analyzed, the harness program should be statically linked against the library / program.

**Comment by flyfish101** [comment]
thanks!
